name: Cypress Test

on: [push]

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps: 
      - name: Get Code
        uses: actions/checkout@v3.3.0

      - name: install dependencies
        run: yarn install

      - name: Run e2e tests
        run: yarn cypress run
     


